version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
